src/Entity/Campus.php
<?php

namespace App\Entity;

use App\Repository\CampusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CampusRepository::class)
 */
class Campus
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name_campus;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="campus")
     */
    private $events;

    /**
     * @ORM\OneToMany(targetEntity=Participant::class, mappedBy="campus")
     */
    private $participants;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getNameCampus();
    }


    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setCampus($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getCampus() === $this) {
                $event->setCampus(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNameCampus()
    {
        return $this->name_campus;
    }

    /**
     * @param mixed $name_campus
     */
    public function setNameCampus($name_campus): void
    {
        $this->name_campus = $name_campus;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setCampus($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->contains($participant)) {
            $this->participants->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getCampus() === $this) {
                $participant->setCampus(null);
            }
        }

        return $this;
    }

}

src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNameCity()
    {
        return $this->name_city;
    }

    /**
     * @param mixed $name_city
     */
    public function setNameCity($name_city): void
    {
        $this->name_city = $name_city;
    }

    /**
     * @return mixed
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }

    /**
     * @param mixed $postal_code
     */
    public function setPostalCode($postal_code): void
    {
        $this->postal_code = $postal_code;
    }

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name_city;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $postal_code;


    /**
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="city")
     */
    private $locations;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setCity($this);
        }
        return $this;
    }
  
  public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getCity() === $this) {
                $location->setCity(null);
            }
        }
        return $this;
    }
  
    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="city")
     */
    private $events;

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setCity($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getCity() === $this) {
                $event->setCity(null);
            }
        }

        return $this;
    }

}

src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LocationRepository::class)
 */
class Location
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column (type="string", length=30)
     */
    private $name_location;

    /**
     * @ORM\Column (type="string", length=30, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column (type="decimal", precision=10, scale=8, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column (type="decimal", precision=10, scale=8, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="locations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNameLocation()
    {
        return $this->name_location;
    }

    /**
     * @param mixed $name_location
     */
    public function setNameLocation($name_location): void
    {
        $this->name_location = $name_location;
    }

    /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     */
    public function setAddress($address): void
    {
        $this->address = $address;
    }

    /**
     * @return mixed
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * @param mixed $latitude
     */
    public function setLatitude($latitude): void
    {
        $this->latitude = $latitude;
    }

    /**
     * @return mixed
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * @param mixed $longitude
     */
    public function setLongitude($longitude): void
    {
        $this->longitude = $longitude;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="location")
     */
    private $events;

    public function __construct()
    {
        $this->events = new ArrayCollection();
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setLocation($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getLocation() === $this) {
                $event->setLocation(null);
            }
        }

        return $this;
    }
}

src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass=ParticipantRepository::class)
 */
class Participant implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
/*TODO ici il y a des unique qui pourront deranger plus tard*/

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=30, unique=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $admin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="organizer")
     */
    private $events;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="participants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campus;

    public function __construct()
    {
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    public function getAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getRoles()
    {
        if ($this->getAdmin()==1){
            return[
                'ROLE_ADMIN'
            ];
        }
        return[
                'ROLE_USER'
            ];
    }
    //Obligé de faire ces 2 fonctions vides pour pouvoir utiliser getRoles
    public function getSalt(){}
    public function eraseCredentials(){}
    //Pour utiliser Serialiaze
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->last_name,
            $this->first_name,
            $this->telephone,
            $this->email,
            $this->password,
            $this->admin,
            $this->active,
            $this->campus

        ]);
    }
    public function unserialize($string)
    {
        list(
            $this->id,
            $this->username,
            $this->last_name,
            $this->first_name,
            $this->telephone,
            $this->email,
            $this->password,
            $this->admin,
            $this->active,
            $this->campus
            ) = unserialize($string, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setOrganizer($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getOrganizer() === $this) {
                $event->setOrganizer(null);
            }
        }

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }


}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\City;
use App\Entity\Event;
use App\Entity\Location;
use App\Entity\Participant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Security\Core\Security;

class EventType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la sortie'
            ])
            ->add('startDate', DateTimeType::class, [
                'label' => 'Date et heure de la sortie'
            ])
            ->add('endDate', DateType::class, [
                'label' => 'Date limite d\'inscription'
            ])
            ->add('duration', IntegerType::class, [
                'label' => 'Durée en heures'
            ])
            ->add('maxRegistrations', IntegerType::class, [
                'label' => 'Nombre de places'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description et infos'
            ])
            ->add('organizer', EntityType::class, [
                'class' => Participant::class,
                'choice_label' => 'first_name',
            ])
            ->add('stateNumState', IntegerType::class, [
                'data' => 1,
            ])
            ->add('campus', EntityType::class, [
                'class' => Campus::class,
                'choice_label' => 'name_campus',
            ])
            ->add('city', EntityType::class, [
            'class' => City::class,
            'choice_label' => 'name_city',
            ])
            ->add('location', EntityType::class, [
                'class' => Location::class,
                'choice_label' => 'name_location'
            ]);


        /* todo: ajouter les reste des attributs: Lieu, Rue, Code postal, Latitude, Longitude  */
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cette sortie?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger">Supprimer la sortie</button>
</form>

templates/event/_filter_form.html.twig
{# todo: gerer le formulaire / tous les filtres #}
<form action="" method="get" class="filters row">
    <div class="col-md-5">
        <select class="custom-select select-campus" name="filter[campus]">
            <option selected>Sélectionnez un campus</option>
            {% for cam in campus %}
                <option value={{ cam.id }}>{{ cam.nameCampus }}</option>
            {% endfor %}
        </select>

        <input class="form-control form-control-md mr-3 w-75" type="text" placeholder="Le nom de la sortie" aria-label="Search">

        <div class="datepicker">
            <p>
                        <span>
                            <label for="date-debut">Entre</label>
                            <input type="date" class="form-control" id="date-debut" placeholder="date" aria-label="date" aria-describedby="basic-addon1">
                        </span>
                <span>
                            <label for="date-fin">et</label>
                            <input type="date" class="form-control" id="date-fin" placeholder="date" aria-label="date" aria-describedby="basic-addon1">
                        </span>
            </p>
        </div>

    </div>

    <div class="col-md-5 sorties-checkboxes">
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="organisateurSortie">
            <label class="form-check-label" for="exampleCheck1">Sorties dont je suis l'organisateur/trice</label>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="inscritSortie">
            <label class="form-check-label" for="exampleCheck1">Sorties auxquelles je suis inscrit/e</label>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="pasInscritSortie">
            <label class="form-check-label" for="exampleCheck1">Sorties auxquelles je ne suis pas inscrit/e</label>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="sortiesPassees">
            <label class="form-check-label" for="exampleCheck1">Sorties passées</label>
        </div>
    </div>
    <div class="col-md-2">
        <button type="submit" class="btn btn-primary rechercher-sortie">Rechercher</button>
    </div>

</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>

{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Sorties{% endblock %}

{% block body %}
    <h1>Modifier la sortie</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Enregistrer les modifications'}) }}

    <a href="{{ path('event_index') }}">Retour à la liste</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/event_table.html.twig
<table class="table table-sorties table-responsive">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Nom de la sortie</th>
        <th scope="col">Date de la sortie</th>
        <th scope="col">Duree en heures</th>
        <th scope="col">Clôture</th>
        <th scope="col">Inscrits/places</th>
        <th scope="col">Etat</th>
        <th scope="col">Inscrit</th>
        <th scope="col">Organisateur</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% if events %}
        {% for event in events %}
        <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.startDate ? event.startDate|date('Y-m-d') : '' }}</td>
            <td>{{ event.duration }}</td>
            <td>{{ event.endDate ? event.endDate|date('Y-m-d') : '' }}</td>
            <td>0/{{ event.maxRegistrations }}</td>
            {# todo: Gestion de etat de la sortie: en cours, fermée, ouverte #}
            <td>{{ event.eventState }}</td>
            {# todo: Gestion des inscriptions, afficher "X" dans le tableau si inscrit #}
            <td>X</td>
            <td>{{ event.organizer.getFirstName }} {{ event.organizer.getLastName }}</td>
            <td>
                <a href="{{ path('event_show', {'id': event.id}) }}">Afficher</a>
                {% if app.user.firstname  == event.organizer.firstName %}
                <a href="{{ path('event_edit', {'id': event.id}) }}">Modifier</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="14">Aucune sortie</td>
        </tr>
    {% endif %}
    </tbody>
</table>

templates/event/events-table.html.twig
<table class="table table-sorties">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Nom de la sortie</th>
        <th scope="col">Date de la sortie</th>
        <th scope="col">Duree</th>
        <th scope="col">Clôture</th>
        <th scope="col">Inscrits/places</th>
        <th scope="col">Etat</th>
        <th scope="col">Inscrit</th>
        <th scope="col">Organisateur</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% if events %}
        {% for event in events %}
        <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.startDate ? event.startDate|date('Y-m-d') : '' }}</td>
            <td>{{ event.duration }}</td>
            <td>{{ event.endDate ? event.endDate|date('Y-m-d') : '' }}</td>
            <td>0/{{ event.maxRegistrations }}</td>
            <td>{{ event.eventState }}</td>
            <td>{{ event.locationNumLocation }}</td>
            <td>{{ event.organizer }}</td>
            <td>
                {# todo: créer un conditionnel pour limiter les actions: si l'organisateur de la sortie est l'utilisateur connecté, il peut modifier ou annuler ses event #}
                <a href="{{ path('event_show', {'id': event.id}) }}">show</a>
                <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
            </td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="14">Aucune sortie</td>
        </tr>
    {% endif %}
    </tbody>
</table>

templates/event/events_table.html.twig
<table class="table table-sorties">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Nom de la sortie</th>
        <th scope="col">Date de la sortie</th>
        <th scope="col">Duree</th>
        <th scope="col">Clôture</th>
        <th scope="col">Inscrits/places</th>
        <th scope="col">Etat</th>
        <th scope="col">Inscrit</th>
        <th scope="col">Organisateur</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% if events %}
        {% for event in events %}
        <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.startDate ? event.startDate|date('Y-m-d') : '' }}</td>
            <td>{{ event.duration }}</td>
            <td>{{ event.endDate ? event.endDate|date('Y-m-d') : '' }}</td>
            <td>0/{{ event.maxRegistrations }}</td>
            <td>{{ event.eventState }}</td>
            <td>{{ event.locationNumLocation }}</td>
            <td>{{ event.organizer }}</td>
            <td>
                {# todo: créer un conditionnel pour limiter les actions: si l'organisateur de la sortie est l'utilisateur connecté, il peut modifier ou annuler ses event #}
                <a href="{{ path('event_show', {'id': event.id}) }}">show</a>
                <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
            </td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="14">Aucune sortie</td>
        </tr>
    {% endif %}
    </tbody>
</table>

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sorties{% endblock %}

{% block body %}
    <div class="container">
        <div class="right-block">
            <div>
                <p>Date de jour : {{ "now"|date("d/m/Y") }}</p>
               {# TODO pour l'instant j'ai mis cette condition pour pouvoir continuer de travailler, mais il faudra le gérer autrement#}
                {% if is_granted('ROLE_USER') %}
                <p>Participant : {{ app.user.lastname|upper }} {{ app.user.firstname }}   </p>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') %}
                    <p>Participant : {{ app.user.lastname|upper }} {{ app.user.firstname }}   </p>
                {% endif %}
            </div>
        </div>
    <h2>Filtrer les sorties</h2>

        {% include ('event/_filter_form.html.twig') %}

        {% include('event/event_table.html.twig') %}

        <button type="button" class="btn btn-primary creer-sortie"><a href="{{ path('event_new') }}">Créer une sortie</a></button>
    </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une sortie{% endblock %}

{% block body %}
    <h1>Créer une sortie</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">retour à la liste</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sorties{% endblock %}

{% block body %}
    <h1>Sortie: {{ event.name }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom de la sortie</th>
                <td>{{ event.name }}</td>
            </tr>
            <tr>
                <th>Date et heure de la sortie</th>
                <td>{{ event.startDate ? event.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date limite d'inscription</th>
                <td>{{ event.endDate ? event.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre de places</th>
                <td>{{ event.maxRegistrations }}</td>
            </tr>
            <tr>
                <th> Duree en heures</th>
                <td>{{ event.duration }}</td>
            </tr>

            <tr>
                <th>Description et infos</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Campus</th>
                <td>{{ event.campus.getNameCampus() }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ event.city.nameCity }}</td>
            </tr>

            <tr>
                <th>Lieu</th>
                <td>{{ event.location.nameLocation }}</td>
            </tr>
            <tr>
                <th>Rue</th>
                <td>{{ event.location.address }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ event.location.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ event.location.longitude }}</td>
            </tr>

        </tbody>
    </table>


    <a href="{{ path('event_index') }}">Retour à la liste</a>

    {% if app.user.firstname  == event.organizer.firstName %}
    <button class="btn btn-primary button-style">
        <a href="{{ path('event_edit', {'id': event.id}) }}">modifier</a>
    </button>

    {{ include('event/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}