src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass=ParticipantRepository::class)
 */
class Participant implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
/*TODO ici il y a des unique qui pourront deranger plus tard*/

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=30, unique=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $admin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="organizer")
     */
    private $events;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="participants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $campus;

    public function __construct()
    {
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    public function getAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getRoles()
    {
        if ($this->getAdmin()==1){
            return[
                'ROLE_ADMIN'
            ];
        }
        return[
                'ROLE_USER'
            ];
    }
    //Obligé de faire ces 2 fonctions vides pour pouvoir utiliser getRoles
    public function getSalt(){}
    public function eraseCredentials(){}
    //Pour utiliser Serialiaze
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->last_name,
            $this->first_name,
            $this->telephone,
            $this->email,
            $this->password,
            $this->admin,
            $this->active,
            $this->campus

        ]);
    }
    public function unserialize($string)
    {
        list(
            $this->id,
            $this->username,
            $this->last_name,
            $this->first_name,
            $this->telephone,
            $this->email,
            $this->password,
            $this->admin,
            $this->active,
            $this->campus
            ) = unserialize($string, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setOrganizer($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getOrganizer() === $this) {
                $event->setOrganizer(null);
            }
        }

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }


}

src/Form/ParticipantType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Participant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParticipantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('last_name')
            ->add('first_name')
            ->add('telephone')
            ->add('email')
            ->add('password')
            ->add('campus')
            ->add('campus', EntityType::class, [
                'class' => Campus::class,
                'choice_label' => 'name_campus',
            ])
            /*->add('admin')
            ->add('active')*/
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Participant::class,
        ]);
    }
}

src/Controller/ParticipantController.php
<?php

namespace App\Controller;

use App\Entity\Participant;
use App\Form\ParticipantType;
use App\Repository\ParticipantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/participant")
 */
class ParticipantController extends AbstractController
{
    /**
     * @Route("/mon profil", name="profile_index", methods={"GET"})
     */
    public function profile(): Response
    {
        return $this->render('participant/profile.html.twig');
    }

    /**
     * @Route("/", name="participant_index", methods={"GET"})
     */
    public function index(ParticipantRepository $participantRepository): Response
    {
        return $this->render('participant/index.html.twig', [
            'participants' => $participantRepository->findAll(),
        ]);
    }

// pour encoder le mdp
    private $encoder;
    public function __construct(UserPasswordEncoderInterface $encoder)
    {
        $this->encoder = $encoder;
    }

    /**
     * @Route("/new", name="participant_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $encoder): Response
    {
        $participant = new Participant();
        $form = $this->createForm(ParticipantType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $password = $encoder->encodePassword($participant, $participant->getPassword());
            $participant->setPassword($password);

            //ici on met de base ces valeurs
            $participant->setAdmin(0);
            $participant->setActive(1);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($participant);
            $entityManager->flush();

            return $this->redirectToRoute('participant_index');
        }

        return $this->render('participant/new.html.twig', [
            'participant' => $participant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="participant_show", methods={"GET"})
     */
    public function show(Participant $participant): Response
    {
        return $this->render('participant/show.html.twig', [
            'participant' => $participant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="participant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Participant $participant): Response
    {
        $form = $this->createForm(ParticipantType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('participant_index');
        }

        return $this->render('participant/edit.html.twig', [
            'participant' => $participant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="participant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Participant $participant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$participant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($participant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('participant_index');
    }
}

templates/participant/_delete_form.html.twig
<form method="post" action="{{ path('participant_delete', {'id': participant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ participant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/participant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Participant{% endblock %}

{% block body %}
    <h1>Edit Participant</h1>

    {{ include('participant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('participant_index') }}">back to list</a>

    {{ include('participant/_delete_form.html.twig') }}
{% endblock %}

templates/participant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participant index{% endblock %}

{% block body %}
    <h1>Participant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Last_name</th>
                <th>First_name</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>Password</th>
                <th>Admin</th>
                <th>Active</th>
                <th>Campus</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for participant in participants %}
            <tr>
                <td>{{ participant.id }}</td>
                <td>{{ participant.username }}</td>
                <td>{{ participant.lastName }}</td>
                <td>{{ participant.firstName }}</td>
                <td>{{ participant.telephone }}</td>
                <td>{{ participant.email }}</td>
                <td>{{ participant.password }}</td>
                <td>{{ participant.admin ? 'Yes' : 'No' }}</td>
                <td>{{ participant.active ? 'Yes' : 'No' }}</td>
                <td>{{ participant.campus.getNameCampus }}</td>
                <td>
                    <a href="{{ path('participant_show', {'id': participant.id}) }}">show</a>
                    <a href="{{ path('participant_edit', {'id': participant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('participant_new') }}">Create new</a>
{% endblock %}

templates/participant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Participant{% endblock %}

{% block body %}
    <h1>Inscription</h1>

    {{ include('participant/_form.html.twig') }}

    <a href="{{ path('participant_index') }}">back to list</a>
{% endblock %}

templates/participant/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}
    <h1>Mon profil</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Username</th>
            <td>{{ app.user.username }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ app.user.lastName }}</td>
        </tr>
        <tr>
            <th>Prenom</th>
            <td>{{ app.user.firstName }}</td>
        </tr>
        <tr>
            <th>Telephone</th>
            <td>{{ app.user.telephone }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ app.user.email }}</td>
        </tr>
        <tr>
            <th>Campus</th>
            <td>{{ app.user.campus }}</td>
        </tr>
        </tbody>
    </table>

{% endblock %}

templates/participant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Participant{% endblock %}

{% block body %}
    <h1>Participant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ participant.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ participant.username }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ participant.lastName }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ participant.firstName }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ participant.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ participant.email }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ participant.password }}</td>
            </tr>
            <tr>
                <th>Admin</th>
                <td>{{ participant.admin ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ participant.active ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Campus</th>
                <td>{{ participant.campusNumCampus }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('participant_index') }}">back to list</a>

    <a href="{{ path('participant_edit', {'id': participant.id}) }}">edit</a>

    {{ include('participant/_delete_form.html.twig') }}
{% endblock %}