src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNameCity()
    {
        return $this->name_city;
    }

    /**
     * @param mixed $name_city
     */
    public function setNameCity($name_city): void
    {
        $this->name_city = $name_city;
    }

    /**
     * @return mixed
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }

    /**
     * @param mixed $postal_code
     */
    public function setPostalCode($postal_code): void
    {
        $this->postal_code = $postal_code;
    }

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name_city;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $postal_code;


    /**
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="city")
     */
    private $locations;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setCity($this);
        }
        return $this;
    }
  
  public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getCity() === $this) {
                $location->setCity(null);
            }
        }
        return $this;
    }
  
    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="city")
     */
    private $events;

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setCity($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getCity() === $this) {
                $event->setCity(null);
            }
        }

        return $this;
    }

}

src/Form/CityType.php
<?php

namespace App\Form;

use App\Entity\City;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_city', TextType::class,[
                'label' => 'Ville'
            ])
            ->add('postal_code', TextType::class,[
                'label' => 'Code Postal'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => City::class,
        ]);
    }
}

src/Controller/CityController.php
<?php

namespace App\Controller;

use App\Entity\City;
use App\Form\CityType;
use App\Repository\CityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/city")
 */
class CityController extends AbstractController
{
    /**
     * @Route("/", name="city_index", methods={"GET"})
     */
    public function index(CityRepository $cityRepository): Response
    {
        return $this->render('city/index.html.twig', [
            'cities' => $cityRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="city_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $city = new City();
        $form = $this->createForm(CityType::class, $city);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($city);
            $entityManager->flush();

            return $this->redirectToRoute('city_index');
        }

        return $this->render('city/new.html.twig', [
            'city' => $city,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="city_show", methods={"GET"})
     */
    public function show(City $city): Response
    {
        return $this->render('city/show.html.twig', [
            'city' => $city,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="city_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, City $city): Response
    {
        $form = $this->createForm(CityType::class, $city);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('city_index');
        }

        return $this->render('city/edit.html.twig', [
            'city' => $city,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="city_delete", methods={"DELETE"})
     */
    public function delete(Request $request, City $city): Response
    {
        if ($this->isCsrfTokenValid('delete'.$city->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($city);
            $entityManager->flush();
        }

        return $this->redirectToRoute('city_index');
    }
}

templates/city/_delete_form.html.twig
<form method="post" action="{{ path('city_delete', {'id': city.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cette ville ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ city.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/city/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/city/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la Ville{% endblock %}

{% block body %}
    <h1>Modifier la Ville</h1>

    {{ include('city/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('city_index') }}">Retour à la liste</a>

    {{ include('city/_delete_form.html.twig') }}
{% endblock %}

templates/city/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les villes{% endblock %}

{% block body %}
    <div class="container">
        <div class="center">
            <div>
                <h2>Gérer les villes</h2>
            </div>
        </div>

        <h2>Filtrer les villes</h2>
        <p>Le nom contient</p>
        <form class="search-container" action="/action_page.php" style="margin:auto;max-width:300px">
            <input type="text" placeholder="Rechercher" name="search">
            <button type="submit">Rechercher</button>
        </form>

        <table class="table table-sorties">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Ville</th>
                <th scope="col">Code postal</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>

            <tbody>
            {% for city in cities %}

            <tr>
                <td>{{ city.nameCity }}</td>
                <td>{{ city.postalCode }}</td>
                <td>
                    <a href="{{ path('city_show', {'id': city.id}) }}">Afficher</a>
                    <a href="{{ path('city_edit', {'id': city.id}) }}">Modifier</a>
                </td>
            </tr>
            {% else %}
                <tr>
                    <td colspan="14">Pas de ville</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button type="button" class="btn btn-primary creer-sortie"><a href="{{ path('city_new') }}">Ajouter une Ville</a></button>
    </div>
{% endblock %}

templates/city/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création de Ville{% endblock %}

{% block body %}
    <h1>Création de Ville</h1>

    {{ include('city/_form.html.twig') }}

    <a href="{{ path('city_index') }}">Retour à la liste</a>
{% endblock %}

templates/city/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ville{% endblock %}

{% block body %}
    <h1>Ville</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Identifiant</th>
                <td>{{ city.id }}</td>
            </tr>
            <tr>
                <th>Nom de la Ville</th>
                <td>{{ city.nameCity }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ city.postalCode }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('city_index') }}">Retour à la liste</a>

    <a href="{{ path('city_edit', {'id': city.id}) }}">Modifier</a>

    {{ include('city/_delete_form.html.twig') }}
{% endblock %}